export interface FoodItem {
  name: string;
  calories: number;
  chain?: string;
}

export const FOOD_DB: FoodItem[] = [
  // ── McDonald's ──────────────────────────────────────────
  { name: "Big Mac", calories: 550, chain: "McDonald's" },
  { name: "Double Big Mac", calories: 740, chain: "McDonald's" },
  { name: "Quarter Pounder with Cheese", calories: 520, chain: "McDonald's" },
  { name: "Double Quarter Pounder with Cheese", calories: 740, chain: "McDonald's" },
  { name: "McDouble", calories: 400, chain: "McDonald's" },
  { name: "Hamburger", calories: 250, chain: "McDonald's" },
  { name: "Cheeseburger", calories: 300, chain: "McDonald's" },
  { name: "McChicken", calories: 400, chain: "McDonald's" },
  { name: "McCrispy Sandwich", calories: 470, chain: "McDonald's" },
  { name: "Spicy McCrispy Sandwich", calories: 490, chain: "McDonald's" },
  { name: "McRib", calories: 480, chain: "McDonald's" },
  { name: "Filet-O-Fish", calories: 390, chain: "McDonald's" },
  { name: "6 pc McNuggets", calories: 250, chain: "McDonald's" },
  { name: "10 pc McNuggets", calories: 410, chain: "McDonald's" },
  { name: "20 pc McNuggets", calories: 830, chain: "McDonald's" },
  { name: "McDonald's Large Fries", calories: 490, chain: "McDonald's" },
  { name: "McDonald's Medium Fries", calories: 320, chain: "McDonald's" },
  { name: "McDonald's Small Fries", calories: 230, chain: "McDonald's" },
  { name: "Egg McMuffin", calories: 310, chain: "McDonald's" },
  { name: "Sausage McMuffin with Egg", calories: 480, chain: "McDonald's" },
  { name: "McGriddles Sausage Egg Cheese", calories: 550, chain: "McDonald's" },
  { name: "Hotcakes", calories: 580, chain: "McDonald's" },
  { name: "Hash Browns", calories: 150, chain: "McDonald's" },
  { name: "Sausage Biscuit", calories: 460, chain: "McDonald's" },
  { name: "McFlurry Oreo", calories: 510, chain: "McDonald's" },
  { name: "McFlurry M&M", calories: 650, chain: "McDonald's" },
  { name: "Vanilla Soft Serve Cone", calories: 200, chain: "McDonald's" },
  { name: "Hot Fudge Sundae", calories: 330, chain: "McDonald's" },
  { name: "Apple Pie", calories: 240, chain: "McDonald's" },
  { name: "McDonald's Large Coke", calories: 290, chain: "McDonald's" },
  { name: "McDonald's Medium Coke", calories: 200, chain: "McDonald's" },

  // ── Burger King ─────────────────────────────────────────
  { name: "Whopper", calories: 660, chain: "Burger King" },
  { name: "Double Whopper", calories: 900, chain: "Burger King" },
  { name: "Whopper with Cheese", calories: 710, chain: "Burger King" },
  { name: "Whopper Jr", calories: 310, chain: "Burger King" },
  { name: "Impossible Whopper", calories: 630, chain: "Burger King" },
  { name: "BK Veggie Burger", calories: 390, chain: "Burger King" },
  { name: "Original Chicken Sandwich", calories: 660, chain: "Burger King" },
  { name: "Ch'King Spicy Sandwich", calories: 700, chain: "Burger King" },
  { name: "Chicken Fries 9pc", calories: 280, chain: "Burger King" },
  { name: "Crispy Chicken Sandwich", calories: 660, chain: "Burger King" },
  { name: "BK Large Fries", calories: 430, chain: "Burger King" },
  { name: "BK Medium Fries", calories: 380, chain: "Burger King" },
  { name: "Onion Rings Medium", calories: 410, chain: "Burger King" },
  { name: "BK Croissan'wich Egg Cheese", calories: 300, chain: "Burger King" },
  { name: "Vanilla Milkshake Medium", calories: 560, chain: "Burger King" },
  { name: "Chocolate Milkshake Medium", calories: 580, chain: "Burger King" },

  // ── Wendy's ─────────────────────────────────────────────
  { name: "Dave's Single", calories: 590, chain: "Wendy's" },
  { name: "Dave's Double", calories: 850, chain: "Wendy's" },
  { name: "Dave's Triple", calories: 1090, chain: "Wendy's" },
  { name: "Baconator", calories: 950, chain: "Wendy's" },
  { name: "Son of Baconator", calories: 640, chain: "Wendy's" },
  { name: "Spicy Chicken Sandwich", calories: 470, chain: "Wendy's" },
  { name: "Grilled Chicken Sandwich", calories: 350, chain: "Wendy's" },
  { name: "Classic Chicken Sandwich", calories: 470, chain: "Wendy's" },
  { name: "Wendy's 10pc Spicy Nuggets", calories: 500, chain: "Wendy's" },
  { name: "Wendy's 10pc Nuggets", calories: 420, chain: "Wendy's" },
  { name: "Wendy's Medium Fries", calories: 340, chain: "Wendy's" },
  { name: "Wendy's Large Fries", calories: 480, chain: "Wendy's" },
  { name: "Frosty Medium Chocolate", calories: 460, chain: "Wendy's" },
  { name: "Frosty Medium Vanilla", calories: 460, chain: "Wendy's" },
  { name: "Small Chili", calories: 180, chain: "Wendy's" },
  { name: "Large Chili", calories: 330, chain: "Wendy's" },
  { name: "Apple Pecan Salad Full", calories: 520, chain: "Wendy's" },
  { name: "Caesar Salad Full", calories: 430, chain: "Wendy's" },
  { name: "Breakfast Baconator", calories: 730, chain: "Wendy's" },

  // ── Taco Bell ───────────────────────────────────────────
  { name: "Crunchwrap Supreme", calories: 530, chain: "Taco Bell" },
  { name: "Crunchy Taco", calories: 170, chain: "Taco Bell" },
  { name: "Soft Taco", calories: 180, chain: "Taco Bell" },
  { name: "Doritos Locos Taco", calories: 170, chain: "Taco Bell" },
  { name: "Supreme Crunchy Taco", calories: 190, chain: "Taco Bell" },
  { name: "Burrito Supreme", calories: 400, chain: "Taco Bell" },
  { name: "Bean Burrito", calories: 380, chain: "Taco Bell" },
  { name: "Chicken Quesadilla", calories: 510, chain: "Taco Bell" },
  { name: "Steak Quesadilla", calories: 520, chain: "Taco Bell" },
  { name: "Mexican Pizza", calories: 540, chain: "Taco Bell" },
  { name: "Nacho Bell Grande", calories: 760, chain: "Taco Bell" },
  { name: "Chalupa Supreme Chicken", calories: 350, chain: "Taco Bell" },
  { name: "Cheesy Gordita Crunch", calories: 490, chain: "Taco Bell" },
  { name: "Nachos BellGrande", calories: 760, chain: "Taco Bell" },
  { name: "Cheesy Fiesta Potatoes", calories: 280, chain: "Taco Bell" },
  { name: "Cinnabon Delights 2pc", calories: 160, chain: "Taco Bell" },
  { name: "Taco Bell Large Drink", calories: 280, chain: "Taco Bell" },
  { name: "Cantina Chicken Bowl", calories: 490, chain: "Taco Bell" },

  // ── Chick-fil-A ─────────────────────────────────────────
  { name: "Chick-fil-A Sandwich", calories: 440, chain: "Chick-fil-A" },
  { name: "Spicy Chicken Sandwich", calories: 450, chain: "Chick-fil-A" },
  { name: "Spicy Deluxe Sandwich", calories: 550, chain: "Chick-fil-A" },
  { name: "Deluxe Chicken Sandwich", calories: 500, chain: "Chick-fil-A" },
  { name: "Grilled Chicken Sandwich", calories: 320, chain: "Chick-fil-A" },
  { name: "Grilled Chicken Club", calories: 430, chain: "Chick-fil-A" },
  { name: "8pc Chick-fil-A Nuggets", calories: 250, chain: "Chick-fil-A" },
  { name: "12pc Chick-fil-A Nuggets", calories: 380, chain: "Chick-fil-A" },
  { name: "Spicy Nuggets 8pc", calories: 260, chain: "Chick-fil-A" },
  { name: "3pc Chick-n-Strips", calories: 340, chain: "Chick-fil-A" },
  { name: "Waffle Fries Medium", calories: 420, chain: "Chick-fil-A" },
  { name: "Waffle Fries Large", calories: 530, chain: "Chick-fil-A" },
  { name: "Mac and Cheese Chick-fil-A", calories: 440, chain: "Chick-fil-A" },
  { name: "Chicken Noodle Soup", calories: 220, chain: "Chick-fil-A" },
  { name: "Cole Slaw Chick-fil-A", calories: 260, chain: "Chick-fil-A" },
  { name: "Chocolate Chunk Cookie", calories: 350, chain: "Chick-fil-A" },
  { name: "Peach Milkshake", calories: 580, chain: "Chick-fil-A" },
  { name: "Cookies and Cream Milkshake", calories: 590, chain: "Chick-fil-A" },
  { name: "Frosted Lemonade", calories: 330, chain: "Chick-fil-A" },
  { name: "Chick-fil-A Breakfast Burrito", calories: 450, chain: "Chick-fil-A" },
  { name: "Hash Brown Scramble Burrito", calories: 700, chain: "Chick-fil-A" },

  // ── KFC ─────────────────────────────────────────────────
  { name: "KFC Original Recipe Breast", calories: 390, chain: "KFC" },
  { name: "KFC Extra Crispy Breast", calories: 530, chain: "KFC" },
  { name: "KFC Original Recipe Thigh", calories: 280, chain: "KFC" },
  { name: "KFC Drumstick", calories: 130, chain: "KFC" },
  { name: "KFC Chicken Wing", calories: 130, chain: "KFC" },
  { name: "3pc KFC Tenders", calories: 340, chain: "KFC" },
  { name: "KFC Chicken Pot Pie", calories: 720, chain: "KFC" },
  { name: "KFC Famous Bowl", calories: 710, chain: "KFC" },
  { name: "KFC Mashed Potatoes with Gravy", calories: 120, chain: "KFC" },
  { name: "KFC Mac and Cheese", calories: 130, chain: "KFC" },
  { name: "KFC Cole Slaw", calories: 110, chain: "KFC" },
  { name: "KFC Biscuit", calories: 180, chain: "KFC" },
  { name: "KFC Corn on the Cob", calories: 70, chain: "KFC" },
  { name: "KFC Green Beans", calories: 25, chain: "KFC" },
  { name: "Chicken Sandwich KFC", calories: 650, chain: "KFC" },
  { name: "Spicy Chicken Sandwich KFC", calories: 610, chain: "KFC" },

  // ── Popeyes ─────────────────────────────────────────────
  { name: "Popeyes Classic Chicken Sandwich", calories: 699, chain: "Popeyes" },
  { name: "Popeyes Spicy Chicken Sandwich", calories: 700, chain: "Popeyes" },
  { name: "Popeyes Chicken Breast", calories: 440, chain: "Popeyes" },
  { name: "Popeyes Spicy Chicken Breast", calories: 440, chain: "Popeyes" },
  { name: "Popeyes 3pc Tenders", calories: 330, chain: "Popeyes" },
  { name: "Popeyes 5pc Tenders", calories: 550, chain: "Popeyes" },
  { name: "Red Beans and Rice", calories: 230, chain: "Popeyes" },
  { name: "Popeyes Biscuit", calories: 260, chain: "Popeyes" },
  { name: "Popeyes Coleslaw", calories: 120, chain: "Popeyes" },
  { name: "Cajun Fries Large", calories: 700, chain: "Popeyes" },
  { name: "Cajun Fries Medium", calories: 570, chain: "Popeyes" },
  { name: "Mac and Cheese Popeyes", calories: 220, chain: "Popeyes" },
  { name: "Mashed Potatoes Popeyes", calories: 110, chain: "Popeyes" },

  // ── Subway (6-inch) ──────────────────────────────────────
  { name: "Subway Meatball Marinara 6\"", calories: 480, chain: "Subway" },
  { name: "Subway Italian BMT 6\"", calories: 410, chain: "Subway" },
  { name: "Subway Turkey Breast 6\"", calories: 280, chain: "Subway" },
  { name: "Subway Chicken Teriyaki 6\"", calories: 310, chain: "Subway" },
  { name: "Subway BLT 6\"", calories: 320, chain: "Subway" },
  { name: "Subway Tuna 6\"", calories: 480, chain: "Subway" },
  { name: "Subway Veggie Delite 6\"", calories: 200, chain: "Subway" },
  { name: "Subway Steak and Cheese 6\"", calories: 380, chain: "Subway" },
  { name: "Subway Club 6\"", calories: 310, chain: "Subway" },
  { name: "Subway Spicy Italian 6\"", calories: 480, chain: "Subway" },
  { name: "Subway Roast Beef 6\"", calories: 320, chain: "Subway" },
  { name: "Subway Black Forest Ham 6\"", calories: 290, chain: "Subway" },
  { name: "Subway Footlong Meatball", calories: 960, chain: "Subway" },
  { name: "Subway Footlong Turkey", calories: 560, chain: "Subway" },
  { name: "Subway Cookies", calories: 210, chain: "Subway" },

  // ── Chipotle ────────────────────────────────────────────
  { name: "Chipotle Chicken Burrito", calories: 910, chain: "Chipotle" },
  { name: "Chipotle Steak Burrito", calories: 920, chain: "Chipotle" },
  { name: "Chipotle Carnitas Burrito", calories: 940, chain: "Chipotle" },
  { name: "Chipotle Chicken Burrito Bowl", calories: 665, chain: "Chipotle" },
  { name: "Chipotle Steak Burrito Bowl", calories: 670, chain: "Chipotle" },
  { name: "Chipotle Veggie Burrito Bowl", calories: 530, chain: "Chipotle" },
  { name: "Chipotle Chicken Tacos (3)", calories: 480, chain: "Chipotle" },
  { name: "Chipotle Steak Tacos (3)", calories: 490, chain: "Chipotle" },
  { name: "Chipotle Chicken Quesadilla", calories: 770, chain: "Chipotle" },
  { name: "Chipotle Chips and Guacamole", calories: 770, chain: "Chipotle" },
  { name: "Chipotle Chips and Salsa", calories: 580, chain: "Chipotle" },
  { name: "Chipotle Kids Meal", calories: 300, chain: "Chipotle" },
  { name: "Chipotle Sofritas Burrito Bowl", calories: 615, chain: "Chipotle" },
  { name: "Chipotle Barbacoa Burrito Bowl", calories: 650, chain: "Chipotle" },

  // ── Domino's (2 slices, large pizza) ────────────────────
  { name: "Domino's Cheese Pizza 2 slices", calories: 510, chain: "Domino's" },
  { name: "Domino's Pepperoni Pizza 2 slices", calories: 570, chain: "Domino's" },
  { name: "Domino's BBQ Chicken Pizza 2 slices", calories: 540, chain: "Domino's" },
  { name: "Domino's Buffalo Chicken Pizza 2 slices", calories: 520, chain: "Domino's" },
  { name: "Domino's Meat Lovers 2 slices", calories: 640, chain: "Domino's" },
  { name: "Domino's Veggie Pizza 2 slices", calories: 460, chain: "Domino's" },
  { name: "Domino's Handmade Pan Cheese 2 slices", calories: 600, chain: "Domino's" },
  { name: "Domino's Breadsticks 2pc", calories: 200, chain: "Domino's" },
  { name: "Domino's Cheesy Bread 2pc", calories: 270, chain: "Domino's" },
  { name: "Domino's Lava Cake", calories: 370, chain: "Domino's" },
  { name: "Domino's Wings 8pc", calories: 670, chain: "Domino's" },

  // ── Pizza Hut (2 slices, medium) ────────────────────────
  { name: "Pizza Hut Cheese Pizza 2 slices", calories: 500, chain: "Pizza Hut" },
  { name: "Pizza Hut Pepperoni Pizza 2 slices", calories: 560, chain: "Pizza Hut" },
  { name: "Pizza Hut Meat Lovers 2 slices", calories: 730, chain: "Pizza Hut" },
  { name: "Pizza Hut Veggie Lovers 2 slices", calories: 440, chain: "Pizza Hut" },
  { name: "Pizza Hut Pepperoni Lovers 2 slices", calories: 660, chain: "Pizza Hut" },
  { name: "Pizza Hut Breadsticks 2pc", calories: 170, chain: "Pizza Hut" },
  { name: "Pizza Hut Cinnabon Mini Rolls 2pc", calories: 160, chain: "Pizza Hut" },
  { name: "Pizza Hut WingStreet Wings 4pc", calories: 280, chain: "Pizza Hut" },

  // ── Starbucks ───────────────────────────────────────────
  { name: "Caramel Macchiato Grande", calories: 250, chain: "Starbucks" },
  { name: "Starbucks Caramel Frappuccino Grande", calories: 380, chain: "Starbucks" },
  { name: "Mocha Frappuccino Grande", calories: 370, chain: "Starbucks" },
  { name: "Java Chip Frappuccino Grande", calories: 460, chain: "Starbucks" },
  { name: "Vanilla Latte Grande", calories: 250, chain: "Starbucks" },
  { name: "Mocha Latte Grande", calories: 290, chain: "Starbucks" },
  { name: "Pumpkin Spice Latte Grande", calories: 380, chain: "Starbucks" },
  { name: "Matcha Green Tea Latte Grande", calories: 240, chain: "Starbucks" },
  { name: "Iced Brown Sugar Oat Shaken Espresso", calories: 120, chain: "Starbucks" },
  { name: "Vanilla Sweet Cream Cold Brew", calories: 110, chain: "Starbucks" },
  { name: "Caramel Ribbon Crunch Frappuccino", calories: 470, chain: "Starbucks" },
  { name: "Starbucks Chocolate Croissant", calories: 340, chain: "Starbucks" },
  { name: "Starbucks Banana Bread", calories: 420, chain: "Starbucks" },
  { name: "Starbucks Cheese Danish", calories: 290, chain: "Starbucks" },
  { name: "Starbucks Egg Bites Bacon Gruyere", calories: 300, chain: "Starbucks" },
  { name: "Starbucks Spinach Feta Wrap", calories: 290, chain: "Starbucks" },
  { name: "Starbucks Turkey Sandwich", calories: 490, chain: "Starbucks" },
  { name: "Starbucks Blueberry Muffin", calories: 380, chain: "Starbucks" },
  { name: "Pink Drink Grande", calories: 140, chain: "Starbucks" },
  { name: "Starbucks Refreshers Grande", calories: 90, chain: "Starbucks" },

  // ── Dunkin' ─────────────────────────────────────────────
  { name: "Glazed Donut Dunkin", calories: 260, chain: "Dunkin'" },
  { name: "Boston Kreme Donut", calories: 300, chain: "Dunkin'" },
  { name: "Dunkin' Chocolate Frosted Donut", calories: 270, chain: "Dunkin'" },
  { name: "Dunkin' Old Fashioned Donut", calories: 290, chain: "Dunkin'" },
  { name: "Dunkin' Jelly Donut", calories: 270, chain: "Dunkin'" },
  { name: "Dunkin' Munchkins 5pc", calories: 200, chain: "Dunkin'" },
  { name: "Dunkin' Croissant", calories: 340, chain: "Dunkin'" },
  { name: "Dunkin' Hash Browns", calories: 200, chain: "Dunkin'" },
  { name: "Dunkin' Egg Cheese Sandwich", calories: 450, chain: "Dunkin'" },
  { name: "Dunkin' Bacon Egg Cheese", calories: 490, chain: "Dunkin'" },
  { name: "Dunkin' Medium Latte", calories: 120, chain: "Dunkin'" },
  { name: "Dunkin' Iced Coffee Medium", calories: 70, chain: "Dunkin'" },

  // ── Panera Bread ────────────────────────────────────────
  { name: "Panera Broccoli Cheddar Soup", calories: 360, chain: "Panera" },
  { name: "Panera Chicken Noodle Soup", calories: 120, chain: "Panera" },
  { name: "Panera Baked Potato Soup", calories: 270, chain: "Panera" },
  { name: "Panera Turkey Sandwich", calories: 500, chain: "Panera" },
  { name: "Panera Frontega Chicken Sandwich", calories: 680, chain: "Panera" },
  { name: "Panera Chicken Bacon Ranch Sandwich", calories: 800, chain: "Panera" },
  { name: "Panera Mac and Cheese", calories: 470, chain: "Panera" },
  { name: "Panera Greek Salad", calories: 380, chain: "Panera" },
  { name: "Panera Caesar Salad", calories: 360, chain: "Panera" },
  { name: "Panera Fuji Apple Salad with Chicken", calories: 570, chain: "Panera" },
  { name: "Panera Cinnamon Crunch Bagel", calories: 430, chain: "Panera" },
  { name: "Panera Asiago Bagel", calories: 300, chain: "Panera" },
  { name: "Panera Muffin Blueberry", calories: 430, chain: "Panera" },
  { name: "Panera Chocolate Chip Cookie", calories: 440, chain: "Panera" },
  { name: "Panera Chipotle Chicken Flatbread", calories: 620, chain: "Panera" },

  // ── Panda Express ───────────────────────────────────────
  { name: "Panda Orange Chicken", calories: 490, chain: "Panda Express" },
  { name: "Panda Beijing Beef", calories: 470, chain: "Panda Express" },
  { name: "Panda Kung Pao Chicken", calories: 290, chain: "Panda Express" },
  { name: "Panda Broccoli Beef", calories: 150, chain: "Panda Express" },
  { name: "Panda String Bean Chicken Breast", calories: 190, chain: "Panda Express" },
  { name: "Panda Honey Walnut Shrimp", calories: 360, chain: "Panda Express" },
  { name: "Panda Mushroom Chicken", calories: 220, chain: "Panda Express" },
  { name: "Panda Chow Mein", calories: 510, chain: "Panda Express" },
  { name: "Panda Fried Rice", calories: 520, chain: "Panda Express" },
  { name: "Panda Steamed Rice", calories: 380, chain: "Panda Express" },
  { name: "Panda Super Greens", calories: 90, chain: "Panda Express" },
  { name: "Panda Egg Roll", calories: 200, chain: "Panda Express" },
  { name: "Panda Spring Roll", calories: 80, chain: "Panda Express" },
  { name: "Panda Chicken Egg Roll", calories: 200, chain: "Panda Express" },
  { name: "Panda Bowl with Orange Chicken", calories: 870, chain: "Panda Express" },
  { name: "Panda Plate with Orange Chicken", calories: 1010, chain: "Panda Express" },

  // ── Five Guys ───────────────────────────────────────────
  { name: "Five Guys Hamburger", calories: 700, chain: "Five Guys" },
  { name: "Five Guys Cheeseburger", calories: 840, chain: "Five Guys" },
  { name: "Five Guys Bacon Burger", calories: 780, chain: "Five Guys" },
  { name: "Five Guys Bacon Cheeseburger", calories: 920, chain: "Five Guys" },
  { name: "Five Guys Little Hamburger", calories: 480, chain: "Five Guys" },
  { name: "Five Guys Little Cheeseburger", calories: 550, chain: "Five Guys" },
  { name: "Five Guys Veggie Sandwich", calories: 440, chain: "Five Guys" },
  { name: "Five Guys Hot Dog", calories: 340, chain: "Five Guys" },
  { name: "Five Guys Regular Fries", calories: 953, chain: "Five Guys" },
  { name: "Five Guys Large Fries", calories: 1314, chain: "Five Guys" },
  { name: "Five Guys Cajun Fries Regular", calories: 953, chain: "Five Guys" },
  { name: "Five Guys Vanilla Milkshake", calories: 800, chain: "Five Guys" },
  { name: "Five Guys Chocolate Milkshake", calories: 840, chain: "Five Guys" },

  // ── Shake Shack ─────────────────────────────────────────
  { name: "ShackBurger", calories: 530, chain: "Shake Shack" },
  { name: "Smoke ShackBurger", calories: 540, chain: "Shake Shack" },
  { name: "SmokeShack Double", calories: 820, chain: "Shake Shack" },
  { name: "Shroom Burger", calories: 590, chain: "Shake Shack" },
  { name: "Cheeseburger Shake Shack", calories: 500, chain: "Shake Shack" },
  { name: "Double ShackBurger", calories: 800, chain: "Shake Shack" },
  { name: "Chicken Shack Sandwich", calories: 530, chain: "Shake Shack" },
  { name: "Spicy Chicken Shack", calories: 540, chain: "Shake Shack" },
  { name: "Shake Shack Crinkle Cut Fries", calories: 470, chain: "Shake Shack" },
  { name: "Shake Shack Cheesy Fries", calories: 740, chain: "Shake Shack" },
  { name: "Vanilla Milkshake Shake Shack", calories: 730, chain: "Shake Shack" },
  { name: "Chocolate Milkshake Shake Shack", calories: 760, chain: "Shake Shack" },
  { name: "Black and White Milkshake", calories: 780, chain: "Shake Shack" },

  // ── In-N-Out ────────────────────────────────────────────
  { name: "In-N-Out Hamburger", calories: 390, chain: "In-N-Out" },
  { name: "In-N-Out Cheeseburger", calories: 480, chain: "In-N-Out" },
  { name: "In-N-Out Double-Double", calories: 670, chain: "In-N-Out" },
  { name: "In-N-Out Double-Double Animal Style", calories: 750, chain: "In-N-Out" },
  { name: "In-N-Out 3x3", calories: 860, chain: "In-N-Out" },
  { name: "In-N-Out 4x4", calories: 1050, chain: "In-N-Out" },
  { name: "In-N-Out French Fries", calories: 395, chain: "In-N-Out" },
  { name: "In-N-Out Animal Style Fries", calories: 750, chain: "In-N-Out" },
  { name: "In-N-Out Chocolate Milkshake", calories: 690, chain: "In-N-Out" },
  { name: "In-N-Out Vanilla Milkshake", calories: 680, chain: "In-N-Out" },
  { name: "In-N-Out Strawberry Milkshake", calories: 690, chain: "In-N-Out" },
  { name: "In-N-Out Protein Style Burger", calories: 240, chain: "In-N-Out" },

  // ── Raising Cane's ──────────────────────────────────────
  { name: "Raising Cane's 3 Finger Combo", calories: 575, chain: "Raising Cane's" },
  { name: "Raising Cane's Box Combo", calories: 702, chain: "Raising Cane's" },
  { name: "Raising Cane's Caniac Combo", calories: 1000, chain: "Raising Cane's" },
  { name: "Raising Cane's Chicken Finger", calories: 140, chain: "Raising Cane's" },
  { name: "Raising Cane's Crinkle Fries", calories: 330, chain: "Raising Cane's" },
  { name: "Raising Cane's Texas Toast", calories: 160, chain: "Raising Cane's" },
  { name: "Raising Cane's Coleslaw", calories: 130, chain: "Raising Cane's" },
  { name: "Cane's Sauce", calories: 150, chain: "Raising Cane's" },

  // ── Wingstop ────────────────────────────────────────────
  { name: "Wingstop Bone-In Wings 6pc", calories: 600, chain: "Wingstop" },
  { name: "Wingstop Boneless Wings 6pc", calories: 560, chain: "Wingstop" },
  { name: "Wingstop Lemon Pepper Wings 6pc", calories: 600, chain: "Wingstop" },
  { name: "Wingstop Large Fries", calories: 690, chain: "Wingstop" },
  { name: "Wingstop Cajun Fries Large", calories: 770, chain: "Wingstop" },
  { name: "Wingstop Ranch Dip", calories: 210, chain: "Wingstop" },
  { name: "Wingstop Chicken Sandwich", calories: 530, chain: "Wingstop" },

  // ── Sonic ───────────────────────────────────────────────
  { name: "Sonic Cheeseburger", calories: 590, chain: "Sonic" },
  { name: "Sonic Double Cheeseburger", calories: 870, chain: "Sonic" },
  { name: "Sonic Bacon Double Cheeseburger", calories: 960, chain: "Sonic" },
  { name: "Sonic Crispy Chicken Sandwich", calories: 530, chain: "Sonic" },
  { name: "Sonic Corn Dog", calories: 180, chain: "Sonic" },
  { name: "Sonic Chili Cheese Coney", calories: 370, chain: "Sonic" },
  { name: "Sonic Tater Tots Medium", calories: 360, chain: "Sonic" },
  { name: "Sonic Tater Tots Large", calories: 490, chain: "Sonic" },
  { name: "Sonic Vanilla Shake Medium", calories: 740, chain: "Sonic" },
  { name: "Sonic Chocolate Shake Medium", calories: 790, chain: "Sonic" },
  { name: "Sonic Route 44 Coke", calories: 400, chain: "Sonic" },
  { name: "Sonic Blast Oreo Medium", calories: 760, chain: "Sonic" },

  // ── Arby's ──────────────────────────────────────────────
  { name: "Arby's Classic Roast Beef", calories: 360, chain: "Arby's" },
  { name: "Arby's Beef and Cheddar", calories: 450, chain: "Arby's" },
  { name: "Arby's French Dip", calories: 440, chain: "Arby's" },
  { name: "Arby's Reuben Sandwich", calories: 610, chain: "Arby's" },
  { name: "Arby's Crispy Chicken Sandwich", calories: 540, chain: "Arby's" },
  { name: "Arby's Curly Fries Medium", calories: 410, chain: "Arby's" },
  { name: "Arby's Loaded Curly Fries", calories: 650, chain: "Arby's" },
  { name: "Arby's Mozzarella Sticks", calories: 430, chain: "Arby's" },
  { name: "Arby's Jamocha Shake", calories: 510, chain: "Arby's" },
  { name: "Arby's Turnovers Apple", calories: 250, chain: "Arby's" },

  // ── Jack in the Box ─────────────────────────────────────
  { name: "Jumbo Jack", calories: 590, chain: "Jack in the Box" },
  { name: "Jumbo Jack with Cheese", calories: 650, chain: "Jack in the Box" },
  { name: "Ultimate Cheeseburger Jack", calories: 940, chain: "Jack in the Box" },
  { name: "Sourdough Jack", calories: 710, chain: "Jack in the Box" },
  { name: "Spicy Crispy Chicken Jack", calories: 560, chain: "Jack in the Box" },
  { name: "Jack in the Box Tacos 2pc", calories: 340, chain: "Jack in the Box" },
  { name: "Jack in the Box Curly Fries Medium", calories: 400, chain: "Jack in the Box" },
  { name: "Stuffed Jalapeños 3pc", calories: 230, chain: "Jack in the Box" },
  { name: "Jack in the Box Breakfast Jack", calories: 360, chain: "Jack in the Box" },

  // ── Dairy Queen ─────────────────────────────────────────
  { name: "DQ Blizzard Oreo Medium", calories: 690, chain: "Dairy Queen" },
  { name: "DQ Blizzard M&M Medium", calories: 730, chain: "Dairy Queen" },
  { name: "DQ Blizzard Reese's Medium", calories: 790, chain: "Dairy Queen" },
  { name: "DQ Dipped Cone Medium", calories: 490, chain: "Dairy Queen" },
  { name: "DQ Soft Serve Cone Medium", calories: 330, chain: "Dairy Queen" },
  { name: "DQ Banana Split", calories: 470, chain: "Dairy Queen" },
  { name: "DQ Cheeseburger", calories: 400, chain: "Dairy Queen" },
  { name: "DQ Bacon Cheese GrillBurger", calories: 730, chain: "Dairy Queen" },
  { name: "DQ Chicken Strip Basket 4pc", calories: 1080, chain: "Dairy Queen" },
  { name: "DQ Medium Fries", calories: 340, chain: "Dairy Queen" },

  // ── Whataburger ─────────────────────────────────────────
  { name: "Whataburger Original", calories: 590, chain: "Whataburger" },
  { name: "Whataburger Double", calories: 820, chain: "Whataburger" },
  { name: "Whataburger Triple", calories: 1050, chain: "Whataburger" },
  { name: "Spicy Chicken Sandwich Whataburger", calories: 530, chain: "Whataburger" },
  { name: "Whatachick'n Sandwich", calories: 500, chain: "Whataburger" },
  { name: "Whataburger Patty Melt", calories: 780, chain: "Whataburger" },
  { name: "Whataburger Medium Fries", calories: 360, chain: "Whataburger" },
  { name: "Whataburger Onion Rings Medium", calories: 420, chain: "Whataburger" },
  { name: "Whataburger Apple Pie", calories: 230, chain: "Whataburger" },
  { name: "Whataburger Honey Butter Chicken Biscuit", calories: 500, chain: "Whataburger" },

  // ── Jersey Mike's (regular, white bread) ───────────────
  { name: "Jersey Mike's Club Sub Regular", calories: 690, chain: "Jersey Mike's" },
  { name: "Jersey Mike's Turkey Regular", calories: 580, chain: "Jersey Mike's" },
  { name: "Jersey Mike's Italian Regular", calories: 750, chain: "Jersey Mike's" },
  { name: "Jersey Mike's Philly Cheesesteak Regular", calories: 680, chain: "Jersey Mike's" },
  { name: "Jersey Mike's BLT Regular", calories: 580, chain: "Jersey Mike's" },
  { name: "Jersey Mike's Tuna Regular", calories: 740, chain: "Jersey Mike's" },

  // ── Common generic foods ────────────────────────────────
  { name: "Cheese Pizza Slice", calories: 285 },
  { name: "Pepperoni Pizza Slice", calories: 313 },
  { name: "Caesar Salad", calories: 360 },
  { name: "Chicken Caesar Salad", calories: 470 },
  { name: "Garden Salad", calories: 100 },
  { name: "Grilled Chicken Breast", calories: 165 },
  { name: "Scrambled Eggs 2pc", calories: 180 },
  { name: "Oatmeal", calories: 150 },
  { name: "Banana", calories: 105 },
  { name: "Apple", calories: 95 },
  { name: "Orange", calories: 62 },
  { name: "Greek Yogurt", calories: 100 },
  { name: "Protein Bar", calories: 200 },
  { name: "Protein Shake", calories: 150 },
  { name: "White Rice 1 cup", calories: 242 },
  { name: "Brown Rice 1 cup", calories: 216 },
  { name: "Spaghetti with Marinara", calories: 280 },
  { name: "Grilled Salmon", calories: 208 },
  { name: "Avocado Toast", calories: 290 },
  { name: "Bagel with Cream Cheese", calories: 450 },
  { name: "Peanut Butter and Jelly", calories: 380 },
  { name: "Canned Tuna", calories: 109 },
  { name: "Whole Milk 1 cup", calories: 149 },
  { name: "Orange Juice 1 cup", calories: 112 },
  { name: "Coca-Cola 12oz", calories: 140 },
  { name: "Diet Coke 12oz", calories: 0 },
  { name: "Gatorade 12oz", calories: 80 },
  { name: "Black Coffee", calories: 5 },
  { name: "Latte 12oz", calories: 120 },
];

// Build a lookup map for O(1) calorie resolution
export const FOOD_CALORIE_MAP = new Map(
  FOOD_DB.map(f => [f.name.toLowerCase(), f])
);

export function getSuggestions(query: string, max = 6): FoodItem[] {
  if (!query.trim()) return [];
  const q = query.toLowerCase();
  const starts = FOOD_DB.filter(f => f.name.toLowerCase().startsWith(q));
  const contains = FOOD_DB.filter(
    f => !f.name.toLowerCase().startsWith(q) && f.name.toLowerCase().includes(q)
  );
  return [...starts, ...contains].slice(0, max);
}

export function lookupCalories(name: string): FoodItem | undefined {
  return FOOD_CALORIE_MAP.get(name.toLowerCase());
}
